name: Gh-pages Deploy
run-name: ${{ github.actor }} is deploying to github 🚀
on:
  push:    
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jesshaw/testactionworkflow:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}    
      volumes:
        - ${{ github.workspace }}:/docs
    #   env:
    #     NODE_ENV: development
    #   ports:
    #     - 80
    #   options: --cpus 1
    steps:
      - name: Print Current Directory
        run: ls -al /docs/docs
